baseURL = "https://chainluber.com"
defaultContentLanguage = "en"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT", "404"]
theme = "hugo-product-launch"
title = "Chain Luber"
[markup.goldmark.renderer]
hardWraps = true
[params]
copyright = "© Chain Luber, LLC."
description = "A next generation motorcycle chain lubrication applicator"
favicon = "/pexels-photo-2662134.jpeg"
hidedesignbyline = false
images = ["images/share-image.png"]
title = "Builders Of The Future, Inc."
[params.meta]
keywords = "some, keywords, for, seo, you, know, google, duckduckgo, and, such"
